Mobit/Areas/Admin/Controllers/SliderController.cs
using Mobit.Data.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mobit.Areas.Admin.Controllers
{
    [_Yetki(Roles = "Admin")]
    public class SliderController : Controller
    {
        Entities db = new Entities();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var slider = db.Slider.OrderBy(s => s.SliderKategori.SliderId).OrderBy(k => k.SliderId).ToList();
            return View(slider);
        }

        public ActionResult Create()
        {
            ViewBag.SliderId = new SelectList(db.SliderKategori.ToList(), "SliderId", "SliderAdi");

            return View();
        }
        public ActionResult SiraGetir(int SliderId)
        {
            
           var sira = db.Slider.Where(s => s.SliderId == SliderId).OrderByDescending(sl => sl.Sira).Select(s => s.Sira).FirstOrDefault();

            sira = sira + 1;
            return Content(sira.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Slider Slider, HttpPostedFileBase Resim)
        {
            ViewBag.SliderId = new SelectList(db.SliderKategori.ToList(), "SliderId", "SliderAdi");

            if (Slider.Baslik == null)
            {
                RedirectToAction("Index");
            }

            if (Resim == null)
            {
                ViewBag.hata = "Lütfen bir resim seçiniz";
                return View();
            }

            Random rnd = new Random();
            string resimAdi = Path.GetFileNameWithoutExtension(Resim.FileName) + "-" + rnd.Next(1, 100000) + Path.GetExtension(Resim.FileName);
            var yuklemeYeri = Path.Combine(Server.MapPath("~/Upload/slide"), resimAdi);
            Resim.SaveAs(yuklemeYeri);

            string target = "_blank";
            if (Slider.Target == "false")
                target = "_self";

            Slider.Target = target;
            Slider.Resim = resimAdi;
            Slider.Tarih = DateTime.Now;
            Slider.Aktif = true;
            db.Slider.Add(Slider);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var slider = db.Slider.Find(id);


            if (slider == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Target = slider.Target;
            ViewBag.SliderId = new SelectList(db.SliderKategori.ToList(), "SliderId", "SliderAdi", slider.SliderId);

            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Slider Slider, HttpPostedFileBase Resim)
        {
            ViewBag.SliderId = new SelectList(db.SliderKategori.ToList(), "SliderId", "SliderAdi", Slider.SliderId);

            if (Slider.Baslik == null)
            {
                RedirectToAction("Index");
            }

            Slider sld = db.Slider.Find(Slider.Id);

            if (Resim == null)
            {
                sld.Resim = sld.Resim;
            }
            else
            {
                Random rnd = new Random();
                string resimAdi = Path.GetFileNameWithoutExtension(Resim.FileName) + "-" + rnd.Next(1, 100000) + Path.GetExtension(Resim.FileName);
                var yuklemeYeri = Path.Combine(Server.MapPath("~/Upload/slide"), resimAdi);
                Resim.SaveAs(yuklemeYeri);

                sld.Resim = resimAdi;
            }

            string target = "_blank";
            if (Slider.Target == "false")
                target = "_self";

            sld.Target = target;
            sld.SliderId = Slider.SliderId;
            sld.Baslik = Slider.Baslik;
            sld.Sira = Slider.Sira;
            sld.Url = Slider.Url;
            sld.Aktif = Slider.Aktif;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            Slider slider = db.Slider.Find(id);

            if (slider == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                FileInfo dosya = new FileInfo(Server.MapPath("~/Upload/slide/" + slider.Resim));

                if (dosya != null)
                {
                    //dosya.Decrypt();
                }
            }
            catch (Exception)
            {
            }

            db.Slider.Remove(slider);
            db.SaveChanges();


            return RedirectToAction("Index");

        }

        public ActionResult RowChange(int id, int? fromPosition, int? toPosition, string direction)
        {
            //if (direction == "back")
            //{
            //    var slides = db.Slider.Where(s => (toPosition <= s.Sira && s.Sira <= fromPosition)).ToList();

            //    if (slides != null)
            //    {
            //        var sld = slides.FirstOrDefault(s => s.Id == id);
            //        sld.Sira = Convert.ToInt32(toPosition);
            //        foreach (var item in slides)
            //        {
            //            if (item.Id != sld.Id)
            //            {
            //                item.Sira++;
            //            }
            //        }
            //    }
            //}
            //else// forward
            //{
            //    var slides = db.Slider.Where(s => (fromPosition <= s.Sira && s.Sira <= toPosition)).ToList();

            //    if (slides != null)
            //    {
            //        var sld = slides.FirstOrDefault(s => s.Id == id);
            //        sld.Sira = Convert.ToInt32(toPosition);
            //        foreach (var item in slides)
            //        {
            //            if (item.Id != sld.Id)
            //            {
            //                item.Sira--;
            //            }
            //        }
            //    }
            //}


            //db.SaveChanges();
            return null;
        }

    }
}

Mobit/Areas/Admin/Views/Slider/Create.cshtml
@model Mobit.Data.Context.Slider

@{
    ViewBag.Title = "Slider Oluştur";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("Create", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slider Oluştur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SliderId, "Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("SliderId", null, "Kategori Seçiniz", htmlAttributes: new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.SliderId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sira, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Sira, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Sira, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Yeni Sekmede Aç</label>
            <div class="col-md-6">
                @Html.CheckBox("Target", true)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-6">
                <input type="file" id="Resim" name="Resim" accept="image/*" /> <b class="text-danger"> @ViewBag.hata</b>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Kaydet" class="btn btn-primary" />


            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

@Scripts.Render("~/admin/bundles/jqueryval")

@section scripts{
    <script>
        $("document").ready(function () {

            $("#Resim").change(function () {

                var ext = $('#Resim').val().split('.').pop().toLowerCase();
                if ($.inArray(ext, ['png', 'jpeg', 'jpg', 'gif', 'bmp']) == -1) {
                    alert('Sadece resim dosyaları seçebilirsiniz.');

                    fileTypeControl($("#Resim"));
                }

            });

        });

        function fileTypeControl(dosya) {
            var fileopen = dosya,
            clone = fileopen.clone(true);
            fileopen.replaceWith(clone);
        }
    </script>

    <script>

        $('#SliderId').change(function () {
            var SliderId = $(this).val();

            if (SliderId != null && SliderId != '') {
                $.ajax({
                    type: "post",
                    url: "/Admin/Slider/SiraGetir",
                    data: { SliderId: SliderId },
                    success: function (sira) {
                        if (sira >= 1) {
                            $("#Sira").val(sira);
                        }
                    },
                    error: function (kategoriler) {

                        //alert("Hata: Sıra getirilemedi");
                    },
                    beforeSend: function () {

                    },
                    complete: function () {

                    }
                });

            }
        });

    </script>

}

Mobit/Areas/Admin/Views/Slider/Edit.cshtml
@model Mobit.Data.Context.Slider

@{
    ViewBag.Title = "Slider Güncelle";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slider Güncelle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
           
            @Html.LabelFor(model => model.SliderId, "Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("SliderId", null, "Kategori Seçiniz", htmlAttributes: new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.SliderId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sira, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Sira, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Sira, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Yeni Sekmede Aç</label>
            <div class="col-md-6">
                @if (Model.Target == "_blank")
                {
                   @Html.CheckBox("Target", true)
                }
                else
                {
                    @Html.CheckBox("Target", false)
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Aktif</label>
            <div class="col-md-6">
                @Html.CheckBox("Aktif")
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-6">
                <input type="file" id="Resim" name="Resim" accept="image/*" />
                @if (Model.Resim != null)
                {
                    <a href="~/Upload/slide/@Model.Resim" target="_blank"><img src="~/Upload/slide/@Model.Resim" width="150" class="img-responsive" alt="@Model.Resim" /></a>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
                <a href="/Admin/Slider/Delete/@Model.Id" onclick="return confirm('Dikkat: Bu kaydı silmek istediğinizden emin misiniz?')" class="btn btn-danger pull-right">Sil</a>


            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

@section scripts{
    <script>
        $("document").ready(function () {

            $("#Resim").change(function () {

                var ext = $('#Resim').val().split('.').pop().toLowerCase();
                if ($.inArray(ext, ['png', 'jpeg', 'jpg', 'gif', 'bmp']) == -1) {
                    alert('Sadece resim dosyaları seçebilirsiniz.');

                    fileTypeControl($("#Resim"));
                }

            });

        });

        function fileTypeControl(dosya) {
            var fileopen = dosya,
            clone = fileopen.clone(true);
            fileopen.replaceWith(clone);
        }
    </script>
}

Mobit/Areas/Admin/Views/Slider/Index.cshtml
@model List<Mobit.Data.Context.Slider>
@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Slider</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>


                </div>
            </div>
            <a class="btn btn-primary" href="/Admin/Slider/Create">Yeni Slider Oluştur</a>
            <div class="ibox-content">

                <table id="example" class="table table-striped table-bordered table-hover dataTables-example" style="width:100%;">
                    <thead>
                        <tr>

                            <th></th>
                            <th width="30">Sıra</th>
                            <th width="30">Resim</th>
                            <th>Başlık</th>
                            <th>Kategori</th>
                            <th>Durum</th>
                            <th>Güncelle</th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr class="gradeX" id="@item.Id">
                                <td>@item.SliderKategori.SliderId</td>
                                <td>@item.Sira</td>
                                <td><a href="~/Upload/slide/@item.Resim" target="_blank"><img src="~/Upload/slide/@item.Resim" class="img-responsive" width="50" alt="@item.Baslik" /></a></td>
                                <td><a href="@item.Url" target="@item.Target"> @item.Baslik </a></td>
                                <td>@item.SliderKategori.SliderAdi</td>
                                @if (item.Aktif == true)
                                {
                                    <td>Aktif</td>
                                }
                                else
                                {
                                    <td><b>Pasif</b></td>
                                }

                                <td><a href="/Admin/Slider/Edit/@item.Id">Güncelle</a></td>

                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/admin/Content/plugins/dataTables/dataTablesStyles")

}

@section Scripts {
    @Scripts.Render("~/admin/plugins/dataTables")
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            var table = $('.dataTables-example').DataTable({

                "order": [[0, "asc"]],
                "scrollX": true,
                "lengthMenu": [[50, 75, 100, -1], [50, 75, 100, "All"]],
                dom: '<"html5buttons"B>lTfgitp',
                responsive: true,

                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'Liste' },
                    { extend: 'pdf', title: 'Liste' },


                    {

                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                        }
                    }
                ]

            });

            table.rowReordering({ sURL: "/Admin/Slider/RowChange" });
        });


    </script>

}