Mobit/Areas/Admin/Controllers/UyeController.cs
using Mobit.Data.Context;
using Mobit.Data.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mobit.Areas.Admin.Controllers
{
    public class UyeController : Controller
    {
        Entities db = new Entities();

        // GET: Admin/Uye
        public ActionResult Index()
        {
            uyeGirdiMi();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Adminler admin)
        {
            admin.Sifre = Kontrol.Base64Encrypt(admin.Sifre);
            var adminGetir = db.Adminler.Where(adm => adm.Mail == admin.Mail && adm.Sifre == admin.Sifre && adm.Aktif == true).FirstOrDefault();

            if (adminGetir != null)
            {
                if (adminGetir.Aktif.ToString() == "False")
                {
                    // ViewBag.msg = "Sayın " + adminGetir.AdSoyad + " üyeliğiniz henüz onaylı değil.";
                    return View();
                }
                else
                {
                    Session["AdminId"] = adminGetir.AdminId;
                    Session["AdSoyad"] = adminGetir.AdSoyad;

                    Session["Yetki"] = db.AdminRolIliski.Where(adm => adm.AdminId == adminGetir.AdminId).Select(adm => adm.AdminRolleri.RolAdi).FirstOrDefault();

                    return Redirect("Home");
                }


            }

            ViewBag.msg = "Lütfen kullanıcı bilgilerinizi kontrol edin.";
            return View();

        }


        [_Yetki]
        public ActionResult Logout()
        {
            Session.Abandon();

            return RedirectToAction("Index");
        }

        public ActionResult SifremiUnuttum()
        {
            uyeGirdiMi();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SifremiUnuttum(string Mail)
        {
            

            if (Mail == null)
            {
                TempData["bilgi"] = "Lütfen mail adresinizi giriniz";
                TempData["class"] = "info";
                return View();
            }

            var personel = db.Adminler.Where(p => p.Mail == Mail).FirstOrDefault();

            if (personel == null)
            {
                TempData["bilgi"] = "Bu mail adresinde kayıtlı kullanıcı bulunamadı.";
                TempData["class"] = "danger";

                return View();
            }

            string yeniSifre = Kontrol.SifreOlustur();
            personel.Sifre = Kontrol.Base64Encrypt(yeniSifre);

            db.SaveChanges();

            TempData["bilgi"] = "Sayın " + personel.AdSoyad + " yeni şifreniz mail adresinize gönderildi.";
            TempData["class"] = "success";

            Helpers.SendMail.Mail("Yeni Şifreniz", "Yeni şifreniz: " + yeniSifre + " <br/>" + Kontrol.SayfaUrlAl(1), personel.Mail);
            return View();
        }

        [_Yetki]
        public ActionResult Profil()
        {
            int AdminId = Convert.ToInt32(Session["AdminId"]);
            var admin = db.Adminler.Where(adm => adm.AdminId == AdminId).FirstOrDefault();

            if (admin == null)
            {
                HttpNotFound();
            }

            return View(admin);
        }

        [_Yetki]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Profil(Adminler admin, string Sifre)
        {

            var adminler = db.Adminler.Where(adm => adm.AdminId == admin.AdminId).FirstOrDefault();

            if (adminler == null)
            {
                HttpNotFound();
            }
            adminler.AdSoyad = admin.AdSoyad;
            adminler.Mail = admin.Mail;


            db.SaveChanges();

            return View();
        }

        [_Yetki]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SifreDegistir(Adminler admin)
        {

            var adminler = db.Adminler.Where(adm => adm.AdminId == admin.AdminId).FirstOrDefault();

            if (adminler == null)
            {
                HttpNotFound();
            }
            adminler.AdSoyad = adminler.AdSoyad;
            adminler.Mail = adminler.Mail;
            adminler.Sifre = Kontrol.Base64Encrypt(admin.Sifre);
            db.SaveChanges();

            return RedirectToAction("Profil");
        }

        void uyeGirdiMi()
        {
            if (Session["AdminId"] != null)
            {
                Response.Redirect("/Admin/Home");
            }
        }

    }
}

Mobit/Areas/Admin/Views/Uye/Index.cshtml
@model Mobit.Data.Context.Adminler
@{
    ViewBag.Title = "Giriş Yap";
    Layout = "~/Areas/Admin/Views/Shared/_Login_Layout.cshtml";
}

<div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
        <div>

            <h1 class="logo-name"></h1> <br /><br />

        </div>
        <h3>Oturum Açın</h3>
        @using (Html.BeginForm("Index", "Uye", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="m-t">
                <div class="form-group">
                    <p class="text-danger">
                        @ViewBag.msg

                    </p>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Mail, new { @class = "control-label pull-left" })
                    @Html.ValidationMessageFor(m => m.Mail, "", new { @class = "text-danger pull-left" })

                    @Html.TextBoxFor(model => model.Mail, new { @class = "form-control" })


                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Sifre, new { @class = "control-label pull-left" })
                    @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger pull-left" })

                    @Html.PasswordFor(model => model.Sifre, new { @class = "form-control", @required = "required" })


                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Giriş Yap</button>

                <a href="Uye/SifremiUnuttum"><small>Şifremi Unuttum</small></a>
                @*<a class="btn btn-sm btn-white btn-block" href="@Url.Action("Yeni", "Uye")">Yeni Üyelik Oluşturun</a>*@
            </div>
        }
    </div>
</div>


@section scripts{

    @Scripts.Render("~/admin/bundles/jqueryval")
}

Mobit/Areas/Admin/Views/Uye/Profil.cshtml
@model Mobit.Data.Context.Adminler

@{
    ViewBag.Title = "Profil";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Profil Bilgilerim <small></small></h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>

            </div>
        </div>
        <div class="ibox-content">
            <div>

                <p class="text-left">Profil bilgilerinizi buradan güncelleyebilirsiniz.</p>
                @if (ViewBag.msj != null)
                {
                    <div class="alert alert-success">
                        @ViewBag.msj
                    </div>
                }
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.AdminId)
                    <div class="form-group">
                        @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-danger" })

                        @Html.LabelFor(model => model.AdSoyad, new { @class = "control-label pull-left" })

                        @Html.TextBoxFor(model => model.AdSoyad, new { @class = "form-control", @required = "required" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Mail, new { @class = "control-label pull-left" })
                        @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })


                        @Html.TextBoxFor(model => model.Mail, new { @class = "form-control", @required = "required" })
                    </div>

                 
                    <div class="form-group">
                        <div class="col-lg-5">
                            <input type="submit" class="btn btn-primary block full-width m-b" value="Bilgilerimi Güncelle" />
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Şifre Değişikliği</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>

            </div>
        </div>
        <div class="ibox-content">

            <p>Şifrenizi buradan değiştirebilirsiniz. </p>
            @if (TempData["sfr"] != null)
            {
                <div class="alert alert-success">
                    @TempData["sfr"]
                </div>
            }
            @using (Html.BeginForm("SifreDegistir", "Uye", FormMethod.Post))
            {
                @Html.AntiForgeryToken();

                @Html.HiddenFor(model => model.AdminId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Sifre, new { @class = "col-lg-2 control-label" })
                    <div class="col-lg-10">
                        @Html.PasswordFor(model => model.Sifre, new { @class = "form-control", @required = "required" })


                        <span class="help-block m-b-none">@Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })</span>
                    </div>
                </div>
                @*<div class="form-group">
                  
                    <label class="col-lg-2 control-label">Şifre Tekrar</label>
                    <div class="col-lg-10">
                        @Html.PasswordFor(model => model.SifreTekrar, new { @class = "form-control" })
                        <span class="help-block m-b-none">@Html.ValidationMessageFor(model => model.SifreTekrar, "", new { @class = "text-danger" })</span>
                    </div>
                </div>*@

                    <div class="form-group">

                        <div class="col-lg-offset-2 col-lg-5">

                            <input type="submit" class="btn btn-primary block full-width m-b" value="Şifremi Değiştir" />
                        </div>
                    </div>

            }
            <br /><br />
            <br /><br /><br /><br /><br />
        </div>
    </div>
</div>
@section scripts{

    @Scripts.Render("~/admin/bundles/jqueryval")
}

Mobit/Areas/Admin/Views/Uye/SifremiUnuttum.cshtml
@model  Mobit.Data.Context.Adminler

@{
    ViewBag.Title = "Şifre Değişikliği";
    Layout = "~/Areas/Admin/Views/Shared/_Login_Layout.cshtml";
}


<div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
        <div>

            <h1 class="logo-name"></h1> <br /><br />

        </div>
        <h3>Yeni Şifrenizi Alın</h3>
        @using (Html.BeginForm("SifremiUnuttum", "Uye", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="m-t">
                <div class="form-group">
                    <p class="text-danger">
                        @ViewBag.msg

                    </p>
                </div>
                <div class="form-group">
                    @if (TempData["bilgi"] != null)
                    {
                        <div class="alert alert-@TempData["class"]">
                            @TempData["bilgi"]
                        </div>
                    }
                    @Html.LabelFor(m => m.Mail, new { @class = "control-label pull-left" })
                    @Html.ValidationMessageFor(m => m.Mail, "", new { @class = "text-danger pull-left" })

                    @Html.TextBoxFor(model => model.Mail, new { @class = "form-control", @required = "required" })


                </div>
               
                <button type="submit" class="btn btn-primary block full-width m-b">Şifremi Gönder</button>

                <a href="/Admin/Uye"><small>Giriş Yap</small></a>
                @*<a class="btn btn-sm btn-white btn-block" href="@Url.Action("Yeni", "Uye")">Yeni Üyelik Oluşturun</a>*@
            </div>
        }
    </div>
</div>


@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
}